name: Build Project Gallery

on:
  push:
    branches:
      - main

jobs:
  build-gallery:

    runs-on: ubuntu-latest

    steps:

      - name: Repository'i indir
        uses: actions/checkout@v4

      - name: Python'u hazırla
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Galeri oluştur
        run: python build_gallery.py

      - name: Değişiklikleri kaydet
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || git commit -m "Otomatik proje galerisi güncellendi"
          git push
